staff-command:
  true:
    admin:
      - "lp user..."
      - "..."
    helper:
      - "lp user..."
      - "..."
  false:
    admin:
      - "lp user..."
      - "..."
    helper:
      - "lp user..."
      - "..."