name: AdminsX
version: '1.0-SNAPSHOT'
main: xyz.vectlabs.adminsx.AdminsX
api-version: 1.13
authors: [ MrFlyn ]
depend:
  - PlaceholderAPI
description: All in one Admin utilities plugin
commands:
  ax:
    description: "main command."
    usage: "/<command>"
permissions:
  adminsx.command:
    default: op
  adminsx.group:
    default: op
